site_name: Privacy & Security Apps and Services — Network Pro™
site_url: https://apps.netwk.pro
repo_url: https://github.com/netwk-pro/privacy-apps/
repo_name: GitHub
docs_dir: src
site_dir: build/

theme:
  name: material
  language: en
  font:
    text: null
    code: null
  logo: img/icon-512x512.png
  favicon: img/favicon.svg
  palette:
    # Default to dark mode
    - scheme: slate
      primary: amber
      accent: yellow
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
    # Optional light mode
    - scheme: default
      primary: deep orange
      accent: orange
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.indexes
    - toc.follow
    - navigation.top
    - search.suggest

markdown_extensions:
  - admonition
  - pymdownx.details # Enables `???` collapsibles
  - pymdownx.superfences # Optional but recommended for nested blocks
  #- toc:
  #    toc_depth: 2 # This limits TOC to H2 only (default is 1-6)

plugins:
  - privacy:
      assets: true
      assets_fetch: true

extra:
  base_url: /
  social:
    - icon: fontawesome/brands/instagram
      name: Network Pro on Instagram
      link: https://instagram.com/netwk_pro
    - icon: fontawesome/brands/facebook
      name: Network Pro on Facebook
      link: https://facebook.com/neteng.pro
    - icon: fontawesome/brands/linkedin
      name: Network Pro on LinkedIn
      link: https://linkedin.com/company/netwk-pro
    - icon: fontawesome/brands/mastodon
      name: Network Pro on Mastodon
      link: https://noc.social/@neteng_pro
    - icon: fontawesome/brands/discord
      name: Network Pro on Discord
      link: https://discord.neteng.pro
    - icon: fontawesome/solid/at
      name: Contact Us
      link: https://netwk.pro/contact

copyright: >
  Copyright &copy; 2025 Network Pro Strategies (Network Pro&trade;) – This site
  does not use cookies. See our <a href="https://netwk.pro/privacy">Privacy
  Policy</a> for details.

nav:
  - Privacy & Security Apps and Services:
      - Overview: index.md
      - App Stores: stores.md
      - 2FA: 2fa.md
      - Browsers: browsers.md
      - Cloud Storage: cloud.md
      - Email Clients: email-clients.md
      - Email Providers: email-providers.md
      - File Encryption: encryption.md
      - File Managers: file-managers.md
      - Gallery and Photo: gallery.md
      - Health and Wellness: health.md
      - Instant Messaging: instant-messaging.md
      - Default Messaging: default-messaging.md
      - Keyboards: keyboards.md
      - Music Players: music.md
      - Navigation (Maps): navigation.md
      - Network Security & Privacy: network-security.md
      - Notes: notes.md
      - Password Managers: password-managers.md
      - PDF Viewers: pdf.md
      - Private DNS: private-dns.md
      - Search Engines: search-engines.md
      - Video Players: video.md
      - VPNs: vpn.md
      - Weather: weather.md
      - Work Profile: work-profile.md
      - YouTube: youtube.md
  - Website: https://netwk.pro
  - Blog: https://blog.netwk.pro
  - Hardening Brave: https://brave.netwk.pro
# cspell:ignore pymdownx superfences collapsibles
